version: '3'
services:
  fe:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3030:3030
    volumes:
      - ./frontend:/src
      - pnpm_store:/src/.pnpm-store
      - node_modules_fe:/src/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    command: sh -c "pnpm run dev"
    depends_on:
      - be

  be:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./backend:/src
      - node_modules_be:/src/node_modules
    command: sh -c "npm start"
    env_file: backend/.env.docker
    depends_on:
      - db

  db:
    image: mongo:5-focal
    volumes:
      - ./backend/docker-entrypoint-initdb.d/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  data:
  pnpm_store:
  node_modules_fe:
  node_modules_be:

