version: '3'
services:
  fe:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3030:3030
    volumes:
      - ./frontend:/src
      - pnpm_store:/src/.pnpm-store
      - node_modules_fe:/src/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    command: sh -c "pnpm run dev"
    depends_on:
      - be

  be:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./backend:/src
      - node_modules_be:/src/node_modules
    command: sh -c "npm start"
    environment:
      - MONGO_URI=mongodb://lab_reporter:lab_reporter1234@db:27017/lab_reporter_dev
      - MONGO_TEST_URI=mongodb://lab_reporter:lab_reporter1234@db:27017/lab_reporter_test
      - PORT=3000
      - JWT_SECRET=lab_reporter1234
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - GOOGLE_DRIVE_TEMPLATES_FOLDER_ID
      - GOOGLE_DRIVE_DELETED_TEMPLATES_FOLDER_ID
      - GOOGLE_DRIVE_REPORTS_FOLDER_ID
      - GOOGLE_DRIVE_DELETED_REPORTS_FOLDER_ID
      - BASE_URL=http://localhost:3000
    depends_on:
      - db

  db:
    image: mongo:5-focal
    volumes:
      - ./backend/docker-entrypoint-initdb.d/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  data:
  pnpm_store:
  node_modules_fe:
  node_modules_be:

